import * as SQLite from 'expo-sqlite';
import { Asset } from 'expo-asset';
import * as FileSystem from 'expo-file-system/legacy';
import AsyncStorage from '@react-native-async-storage/async-storage';
import { logger } from '../lib/logger';
import { Kysely } from 'kysely';
import { ExpoDialect } from 'kysely-expo';
import { Database } from '../data/db/schema';

/**
 * SQLiteKernel
 * The low-level engine room of the MoodMap database infrastructure.
 * Handles the binary payload, file system operations, and kernel attachment.
 */
export class SQLiteKernel {
  // Auto-versioning: reads hash from db_manifest.json generated by compile_registry.ts
  private static readonly DB_NAME = 'moodmap_current.db';
  private static readonly BUNDLED_DB_ASSET = require('../../assets/moodmap.db');
  private static readonly MANIFEST = require('../../assets/db_manifest.json');
  private static readonly VERSION_KEY = 'deployed_db_hash';

  private db: SQLite.SQLiteDatabase | null = null;
  private kyselyDb: Kysely<Database> | null = null;

  constructor() { }

  /**
   * Attaches the SQLite kernel by ensuring the binary is deployed and opened.
   */
  async attach(): Promise<SQLite.SQLiteDatabase> {
    if (this.db) return this.db;

    try {
      const dbDir = `${FileSystem.documentDirectory}SQLite`;
      const dbPath = `${dbDir}/${SQLiteKernel.DB_NAME}`;
      const currentHash = SQLiteKernel.MANIFEST.hash;

      // 1. Ensure Directory
      const dirInfo = await FileSystem.getInfoAsync(dbDir);
      if (!dirInfo.exists) {
        await FileSystem.makeDirectoryAsync(dbDir, { intermediates: true });
      }

      // 1b. Cleanup old versioned DB files (migration from v47-v56 naming)
      try {
        const dirContents = await FileSystem.readDirectoryAsync(dbDir);
        for (const file of dirContents) {
          if (file.startsWith('moodmap_current_v') && file.endsWith('.db')) {
            logger.log(`🗑️ [Kernel] Purging old versioned DB: ${file}`);
            await FileSystem.deleteAsync(`${dbDir}/${file}`, { idempotent: true });
          }
          // Also purge any abandoned WAL/SHM files if the main DB is gone
          if (file.includes('moodmap') && (file.endsWith('-wal') || file.endsWith('-shm'))) {
            await FileSystem.deleteAsync(`${dbDir}/${file}`, { idempotent: true });
          }
        }
      } catch (cleanupError) {
        // Non-fatal: cleanup failure shouldn't block deployment
        logger.log(`⚠️ [Kernel] Cleanup warning: ${cleanupError}`);
      }

      // 2. Binary Deployment Logic
      const asset = Asset.fromModule(SQLiteKernel.BUNDLED_DB_ASSET);
      await asset.downloadAsync();

      if (!asset.localUri) {
        throw new Error('Binary payload missing localUri.');
      }

      const dbInfo = await FileSystem.getInfoAsync(dbPath);
      let shouldDeploy = !dbInfo.exists;

      if (!shouldDeploy) {
        const deployedHash = await AsyncStorage.getItem(SQLiteKernel.VERSION_KEY);
        console.warn(`📊 [Kernel] Hash Check: Deployed=${deployedHash} | Bundled=${currentHash}`);
        if (deployedHash !== currentHash) {
          logger.log(
            `🔄 [Kernel] Hash shift detected (${deployedHash} -> ${currentHash})`,
          );
          // CRITICAL: Must delete WAL and SHM accompanies to prevent malformation
          await FileSystem.deleteAsync(dbPath, { idempotent: true });
          await FileSystem.deleteAsync(`${dbPath}-wal`, { idempotent: true });
          await FileSystem.deleteAsync(`${dbPath}-shm`, { idempotent: true });
          shouldDeploy = true;
        }
      }

      if (shouldDeploy) {
        console.warn(`📥 [Kernel] FORCE DEPLOYMENT of hash: ${currentHash}`);
        logger.log(`📥 [Kernel] Deploying binary (hash: ${currentHash})...`);
        await FileSystem.copyAsync({
          from: asset.localUri,
          to: dbPath,
        });
        await AsyncStorage.setItem(SQLiteKernel.VERSION_KEY, currentHash);
      }

      // 3. Open Database
      try {
        this.db = await SQLite.openDatabaseAsync(SQLiteKernel.DB_NAME);
        // 4. Integrity check — actually verify the result
        const check = await this.db.getFirstAsync<{ integrity_check: string }>('PRAGMA integrity_check;');
        if (check?.integrity_check !== 'ok') {
          throw new Error(`Integrity check failed: ${check?.integrity_check}`);
        }
      } catch (dbError) {
        logger.log(`🔧 [Kernel] DB corrupted or malformed, force redeploying...`);
        // Close any partially opened DB
        if (this.db) {
          try { await this.db.closeAsync(); } catch (_) { }
          this.db = null;
        }
        // Delete and redeploy (Atomically)
        await FileSystem.deleteAsync(dbPath, { idempotent: true });
        await FileSystem.deleteAsync(`${dbPath}-wal`, { idempotent: true });
        await FileSystem.deleteAsync(`${dbPath}-shm`, { idempotent: true });

        await FileSystem.copyAsync({
          from: asset.localUri,
          to: dbPath,
        });
        await AsyncStorage.setItem(SQLiteKernel.VERSION_KEY, currentHash);
        this.db = await SQLite.openDatabaseAsync(SQLiteKernel.DB_NAME);

        // Final sanity check after redeploy
        const finalCheck = await this.db.getFirstAsync<{ integrity_check: string }>('PRAGMA integrity_check;');
        if (finalCheck?.integrity_check !== 'ok') {
          throw new Error(`Fatal: Redepoyed DB is still malformed: ${finalCheck?.integrity_check}`);
        }
      }

      // 5. Performance Tuning (Defensive)
      try {
        await this.db.execAsync('PRAGMA journal_mode = WAL;');
        await this.db.execAsync('PRAGMA synchronous = NORMAL;');
      } catch (tuningError) {
        logger.log(`⚠️ [Kernel] Tuning warning: ${tuningError}`);
      }

      return this.db;
    } catch (error) {
      logger.error(
        `💀 [Kernel] Attachment Failed: ${error instanceof Error ? error.message : 'Unknown'}`,
      );
      throw error;
    }
  }

  async getDatabase(): Promise<SQLite.SQLiteDatabase> {
    if (!this.db) {
      return await this.attach();
    }
    return this.db;
  }

  async getKysely(): Promise<Kysely<Database>> {
    if (!this.kyselyDb) {
      const rawDb = await this.getDatabase();
      this.kyselyDb = new Kysely<Database>({
        dialect: new ExpoDialect({
          database: rawDb,
        }),
      });
    }
    return this.kyselyDb;
  }

  async close() {
    if (this.db) {
      await this.db.closeAsync();
      this.db = null;
    }
    if (this.kyselyDb) {
      await this.kyselyDb.destroy();
      this.kyselyDb = null;
    }
  }
}
